## Assignments -25/05/2020

## File : cancer_classification

### Topic : Classification_models-master

#### Submitted by: Anoop V H

##### Version :

##### Date : 27/05/2020

# Import Required Packages

## Basic Packages

In [24]:
import numpy as np 
import pandas as pd 
import warnings
warnings.filterwarnings('ignore')

## For Splitting Data

In [25]:
from sklearn.model_selection import train_test_split

## Required Machine Learning Models

In [26]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from xgboost import XGBClassifier

## Metrics Required packages

In [27]:
from sklearn import metrics
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

from sklearn.metrics import confusion_matrix

## Import Dataset

In [28]:
df = pd.read_csv("E:\\1\Assignments\\data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

## Data Preprocessing

In [29]:
df.drop(['Unnamed: 32',"id"], axis=1, inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [30]:
df=df.replace({'diagnosis':'M'},0)
df=df.replace({'diagnosis':'B'},1)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          0        17.99         10.38          122.80     1001.0   
1          0        20.57         17.77          132.90     1326.0   
2          0        19.69         21.25          130.00     1203.0   
3          0        11.42         20.38           77.58      386.1   
4          0        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Normalization

## Min-Max Normalization

In [31]:
df = (df -np.min(df))/(np.max(df)-np.min(df)).values

## Data Splitting

In [32]:
y = df.diagnosis.values

In [33]:
x = df.drop(['diagnosis'], axis=1)

### Splitting into training and testing

In [34]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=2)

# Machine Learning Models

## Logistic Regression

In [35]:
# With Default Values
LogisticRegression()

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [36]:
lr=LogisticRegression()

lr.fit(X_train,y_train)

y_pred = lr.predict(X_test)

acc = metrics.accuracy_score(y_test, y_pred)

pre=metrics.precision_score(y_test, y_pred)

f1=metrics.f1_score(y_test, y_pred)

recall=metrics.recall_score(y_test, y_pred)

pre,recall,f1,acc

(0.9347826086956522, 0.9885057471264368, 0.9608938547486033, 0.951048951048951)

In [37]:
conf_mat = confusion_matrix(y_test, y_pred)
TP=conf_mat[0,0]
TN=conf_mat[1,1]
FP=conf_mat[0,1]
FN=conf_mat[1,0]

pre_a=(TP/(TP+FP))
recall_a=(TP/(TP+FN))
f1_a=(2*TP/(2*TP+FN+FP))
acc_a=((TP+TN)/np.sum(conf_mat))

conf_mat,pre_a,recall_a,f1_a,acc_a

(array([[50,  6],
        [ 1, 86]], dtype=int64),
 0.8928571428571429,
 0.9803921568627451,
 0.9345794392523364,
 0.951048951048951)

## Decision Tree 

In [64]:
DecisionTreeClassifier()

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [65]:
dt=DecisionTreeClassifier()

dt.fit(X_train,y_train)

y_pred = dt.predict(X_test)

acc = metrics.accuracy_score(y_test, y_pred)

pre=metrics.precision_score(y_test, y_pred)

f1=metrics.f1_score(y_test, y_pred)

recall=metrics.recall_score(y_test, y_pred)

pre,recall,f1,acc## Gaussian Naive Bayes

(0.9753086419753086,
 0.9080459770114943,
 0.9404761904761905,
 0.9300699300699301)

In [66]:
conf_mat = confusion_matrix(y_test, y_pred)
TP=conf_mat[0,0]
TN=conf_mat[1,1]
FP=conf_mat[0,1]
FN=conf_mat[1,0]

pre_a=(TP/(TP+FP))
recall_a=(TP/(TP+FN))
f1_a=(2*TP/(2*TP+FN+FP))
acc_a=((TP+TN)/np.sum(conf_mat))

conf_mat,pre_a,recall_a,f1_a,acc_a

(array([[54,  2],
        [ 8, 79]], dtype=int64),
 0.9642857142857143,
 0.8709677419354839,
 0.9152542372881356,
 0.9300699300699301)

## Gaussian Naive Bayes

In [41]:
GradientBoostingClassifier()

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [43]:
gnb=GradientBoostingClassifier()

gnb.fit(X_train,y_train)

y_pred = gnb.predict(X_test)

acc = metrics.accuracy_score(y_test, y_pred)

pre=metrics.precision_score(y_test, y_pred)

f1=metrics.f1_score(y_test, y_pred)

recall=metrics.recall_score(y_test, y_pred)

pre,recall,f1,acc

(0.9540229885057471,
 0.9540229885057471,
 0.9540229885057472,
 0.9440559440559441)

In [45]:
conf_mat = confusion_matrix(y_test, y_pred)
TP=conf_mat[0,0]
TN=conf_mat[1,1]
FP=conf_mat[0,1]
FN=conf_mat[1,0]

pre_a=(TP/(TP+FP))
recall_a=(TP/(TP+FN))
f1_a=(2*TP/(2*TP+FN+FP))
acc_a=((TP+TN)/np.sum(conf_mat))

conf_mat,pre_a,recall_a,f1_a,acc_a

(array([[52,  4],
        [ 4, 83]], dtype=int64),
 0.9285714285714286,
 0.9285714285714286,
 0.9285714285714286,
 0.9440559440559441)

## KNN

In [46]:
KNeighborsClassifier()

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [47]:
knn=KNeighborsClassifier()

knn.fit(X_train,y_train)

y_pred = knn.predict(X_test)

acc = metrics.accuracy_score(y_test, y_pred)

pre=metrics.precision_score(y_test, y_pred)

f1=metrics.f1_score(y_test, y_pred)

recall=metrics.recall_score(y_test, y_pred)

pre,recall,f1,acc

(0.9550561797752809, 0.9770114942528736, 0.9659090909090908, 0.958041958041958)

In [48]:
conf_mat = confusion_matrix(y_test, y_pred)
TP=conf_mat[0,0]
TN=conf_mat[1,1]
FP=conf_mat[0,1]
FN=conf_mat[1,0]

pre_a=(TP/(TP+FP))
recall_a=(TP/(TP+FN))
f1_a=(2*TP/(2*TP+FN+FP))
acc_a=((TP+TN)/np.sum(conf_mat))

conf_mat,pre_a,recall_a,f1_a,acc_a

(array([[52,  4],
        [ 2, 85]], dtype=int64),
 0.9285714285714286,
 0.9629629629629629,
 0.9454545454545454,
 0.958041958041958)

## Random Forest

In [49]:
RandomForestClassifier(n_estimators=100,oob_score=True,max_features=5)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features=5, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [50]:
rf=RandomForestClassifier(n_estimators=100,oob_score=True,max_features=5)

rf.fit(X_train,y_train)

y_pred = rf.predict(X_test)

acc = metrics.accuracy_score(y_test, y_pred)

pre=metrics.precision_score(y_test, y_pred)

f1=metrics.f1_score(y_test, y_pred)

recall=metrics.recall_score(y_test, y_pred)

pre,recall,f1,acc

(0.9651162790697675, 0.9540229885057471, 0.9595375722543352, 0.951048951048951)

In [51]:
conf_mat = confusion_matrix(y_test, y_pred)
TP=conf_mat[0,0]
TN=conf_mat[1,1]
FP=conf_mat[0,1]
FN=conf_mat[1,0]

pre_a=(TP/(TP+FP))
recall_a=(TP/(TP+FN))
f1_a=(2*TP/(2*TP+FN+FP))
acc_a=((TP+TN)/np.sum(conf_mat))

conf_mat,pre_a,recall_a,f1_a,acc_a

(array([[53,  3],
        [ 4, 83]], dtype=int64),
 0.9464285714285714,
 0.9298245614035088,
 0.9380530973451328,
 0.951048951048951)

## Support vector machine

In [52]:
SVC()

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [53]:
svc=SVC()

svc.fit(X_train,y_train)

y_pred = svc.predict(X_test)

acc = metrics.accuracy_score(y_test, y_pred)

pre=metrics.precision_score(y_test, y_pred)

f1=metrics.f1_score(y_test, y_pred)

recall=metrics.recall_score(y_test, y_pred)

pre,recall,f1,acc

(0.9347826086956522, 0.9885057471264368, 0.9608938547486033, 0.951048951048951)

In [54]:
conf_mat = confusion_matrix(y_test, y_pred)
TP=conf_mat[0,0]
TN=conf_mat[1,1]
FP=conf_mat[0,1]
FN=conf_mat[1,0]

pre_a=(TP/(TP+FP))
recall_a=(TP/(TP+FN))
f1_a=(2*TP/(2*TP+FN+FP))
acc_a=((TP+TN)/np.sum(conf_mat))

conf_mat,pre_a,recall_a,f1_a,acc_a

(array([[50,  6],
        [ 1, 86]], dtype=int64),
 0.8928571428571429,
 0.9803921568627451,
 0.9345794392523364,
 0.951048951048951)

## Gradient Boost Classifier

In [55]:
GradientBoostingClassifier()

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [56]:
gbc=GradientBoostingClassifier()

gbc.fit(X_train,y_train)

y_pred = gbc.predict(X_test)

acc = metrics.accuracy_score(y_test, y_pred)

pre=metrics.precision_score(y_test, y_pred)

f1=metrics.f1_score(y_test, y_pred)

recall=metrics.recall_score(y_test, y_pred)

pre,recall,f1,acc

(0.9540229885057471,
 0.9540229885057471,
 0.9540229885057472,
 0.9440559440559441)

In [57]:
conf_mat = confusion_matrix(y_test, y_pred)
TP=conf_mat[0,0]
TN=conf_mat[1,1]
FP=conf_mat[0,1]
FN=conf_mat[1,0]

pre_a=(TP/(TP+FP))
recall_a=(TP/(TP+FN))
f1_a=(2*TP/(2*TP+FN+FP))
acc_a=((TP+TN)/np.sum(conf_mat))

conf_mat,pre_a,recall_a,f1_a,acc_a

(array([[52,  4],
        [ 4, 83]], dtype=int64),
 0.9285714285714286,
 0.9285714285714286,
 0.9285714285714286,
 0.9440559440559441)

## Linear Discriminant Analysis

In [58]:
LinearDiscriminantAnalysis()

LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
                           solver='svd', store_covariance=False, tol=0.0001)

In [59]:
lda=LinearDiscriminantAnalysis()

lda.fit(X_train,y_train)

y_pred = lda.predict(X_test)

acc = metrics.accuracy_score(y_test, y_pred)

pre=metrics.precision_score(y_test, y_pred)

f1=metrics.f1_score(y_test, y_pred)

recall=metrics.recall_score(y_test, y_pred)

pre,recall,f1,acc

(0.9456521739130435, 1.0, 0.9720670391061452, 0.965034965034965)

In [60]:
conf_mat = confusion_matrix(y_test, y_pred)
TP=conf_mat[0,0]
TN=conf_mat[1,1]
FP=conf_mat[0,1]
FN=conf_mat[1,0]

pre_a=(TP/(TP+FP))
recall_a=(TP/(TP+FN))
f1_a=(2*TP/(2*TP+FN+FP))
acc_a=((TP+TN)/np.sum(conf_mat))

conf_mat,pre_a,recall_a,f1_a,acc_a

(array([[51,  5],
        [ 0, 87]], dtype=int64),
 0.9107142857142857,
 1.0,
 0.9532710280373832,
 0.965034965034965)

## XGBoost

In [61]:
XGBClassifier()

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [62]:
xgb=XGBClassifier()

xgb.fit(X_train,y_train)

y_pred = xgb.predict(X_test)

acc = metrics.accuracy_score(y_test, y_pred)

pre=metrics.precision_score(y_test, y_pred)

f1=metrics.f1_score(y_test, y_pred)

recall=metrics.recall_score(y_test, y_pred)

pre,recall,f1,acc

(0.9764705882352941, 0.9540229885057471, 0.9651162790697674, 0.958041958041958)

In [63]:
conf_mat = confusion_matrix(y_test, y_pred)
TP=conf_mat[0,0]
TN=conf_mat[1,1]
FP=conf_mat[0,1]
FN=conf_mat[1,0]

pre_a=(TP/(TP+FP))
recall_a=(TP/(TP+FN))
f1_a=(2*TP/(2*TP+FN+FP))
acc_a=((TP+TN)/np.sum(conf_mat))

conf_mat,pre_a,recall_a,f1_a,acc_a

(array([[54,  2],
        [ 4, 83]], dtype=int64),
 0.9642857142857143,
 0.9310344827586207,
 0.9473684210526315,
 0.958041958041958)