## Assignments

## File : Numpy Excersice 1

### Topic : Exercise 1-3

#### Submitted by: Anoop V H

##### Version : 1.0
##### Date's:
##### Start date of assignment : may 12, 2020
##### First Submission date : May 14,2020

### Q1. Find A transpose 

In [1]:
#importing Numpy
import numpy as np

#Creating Matrix A with given elements
matA=np.matrix([[3,4,5],[2,3,1],[2,1,2]])

#calculating the Transpose of the matrix A by use of Numpy Transpose method
trA=np.transpose(matA)

print("Matrix A= \n",matA,"\n \n Transpose of A = \n",trA)

Matrix A= 
 [[3 4 5]
 [2 3 1]
 [2 1 2]] 
 
 Transpose of A = 
 [[3 2 2]
 [4 3 1]
 [5 1 2]]


In [2]:
#Creating Matrix B with given elements 
matB=np.matrix([[2,4],[1,2],[3,1]])
print("Matrix B=\n",matB)

Matrix B=
 [[2 4]
 [1 2]
 [3 1]]


In [3]:
print("Result of Matrix multiplication A*B \n",matA*matB)

Result of Matrix multiplication A*B 
 [[25 25]
 [10 15]
 [11 12]]


### Q2   Here are the salary details of employees. The HR uses a prediction scale of 3 lakhs plus 2 lakhs for every year as the salary. Calculate manually using numpy the sum of square errors in prediction of salary.

In [4]:
#importing numpy 
import numpy as np

#Salary details are enterd to the array in the following pattern
#       ["Employee_id","Years_of_exp","Salary_in_lakhs"]

salaryDetails=np.array([[125,2,6.9],[128,4,12.2],[132,3,9.5],[145,1,4.9]])

#creating another numpy arrray which holds the predicted salary
predictedSalary=3+salaryDetails[:,1]*2

#Calculating the error in the prediction 
errors=salaryDetails[:,2]-predictedSalary

#Calculating Sum of Square errors
sumofSuqare=(sum(errors))**2

print("Salary Details: \n \n",salaryDetails,"\n \nPredicted Salary :\n \n"
      ,predictedSalary,"\n \nErros in the prediction :\n \n",errors,"\n \nSum of Square Erros :  ",sumofSuqare)

Salary Details: 
 
 [[125.    2.    6.9]
 [128.    4.   12.2]
 [132.    3.    9.5]
 [145.    1.    4.9]] 
 
Predicted Salary :
 
 [ 7. 11.  9.  5.] 
 
Erros in the prediction :
 
 [-0.1  1.2  0.5 -0.1] 
 
Sum of Square Erros :   2.25


### Q 3

#### import numpy as np 
#### ar1=np.array([1,3,5,6,4,7])
#### ar2 = ar1 + 3
#### print (ar2)

#### What is the expected output of the following

(1) print(ar1[1])

(2) print(ar1[1:3])

(3) print(ar1[:3])

(4) print(ar1[-3])

(5) print(ar1[-1:3])

In [5]:
#Answers

print("Answers: \n(1) 3\n(2) 3 5\n(3) 1 3 5\n(4) 6\n(5) _____\n")

Answers: 
(1) 3
(2) 3 5
(3) 1 3 5
(4) 6
(5) _____

