## Assignments

## File : Numpy Assignment 1

### Topic : Qusetion 1- 7

#### Submitted by: Anoop V H

##### Version : 1.0
##### Date's:
##### Start date of assignment : Feb 13, 2020
##### First Submission date : Feb 16,2020

## Question 1 :-Write a python program to take a 3X3 matrix as a user input. Convert the matrix into numpy array. Print the matrix, rank, shape of the matrix. ?

In [1]:
#way 1

import numpy as np
#raw = int(input("Enter the no of Raws : \n"))
#column = int(input("Enter the no of Column : \n"))
raw,column=3,3
mat=[]
for i in range(raw*column):
    a=int(input())
    mat.append(a)
#mat=np.array(mat).reshape(raw,column)
mat=np.matrix(mat).reshape(raw,column)
m_array=np.array(mat)
print(type(m_array))

print("Matrix: \n",m_array)
print("Range : ",np.ndim(mat))
print("Shape : ",np.shape(mat))

1
2
3
4
5
6
7
8
9
<class 'numpy.ndarray'>
Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Range :  2
Shape :  (3, 3)


In [2]:
#way 2

import numpy as np
#raw = int(input("Enter the no of Raws : \n"))
#column = int(input("Enter the no of Column : \n"))
raw,column=3,3
#Data entering section
mat=[3*3]
print("Enter the matrix elements (in raw wise and without space)")
mat=map(int,input()) # using map function recevice int values

#converting map to list and then to Numpy matrix and reshaping it
mat=np.matrix(list(mat)).reshape(raw,column)

#converting the numpy matrix to numpy array
m_array=np.array(mat)

#printing the results

print(np.shape(mat))
print("Matrix: \n",m_array)
print("Range : ",np.ndim(mat))
print("Shape : ",np.shape(mat))

#enter the matrix values without space. 
#fault identified : Only single digit values can be entered through this way

Enter the matrix elements (in raw wise and without space)
123456789
(3, 3)
Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Range :  2
Shape :  (3, 3)


## Question 2 :- Write a function that generates 10 integers and use it to build an array 

In [3]:
import numpy as np

# 2nd random int function select a random int value and this is taken as the highest limit of the 1st funciton and it generates
#10 values between that number and zero 
array=np.random.randint(np.random.randint(1000), size=10)
print(array,"\n",array.shape)

[ 38  69 239 476  50 285 408 391 511 104] 
 (10,)


## Question 3 :- Create a random vector (1D array) of size 10 and sort it 

In [4]:
import numpy as np
#creating random array
array=np.random.randint(np.random.randint(1000), size=10)
#sorting it by using sorted funciton
print(sorted(array))
#print(array,"\n",array.shape)

[144, 152, 172, 242, 276, 322, 355, 466, 470, 479]


## Question 4 :- Write a Python program to generate five random numbers from the normal distribution.
#### [Hint: use np.random.normal] 

In [5]:
import numpy as np
# generating random number bet zero and 0.1
randVal=np.random.normal(0,0.1,(5))
print(randVal)

[ 0.06658815  0.06172988  0.10781974  0.08866218 -0.02826081]


## Question 5 :-
### Write a numpy program program to add and subtract two random matrices. The size of the matrix will a user input. All the matrix element should be a positive integer value. Suppose 'A' and 'B' are two matrix. All the value of 'A' matrix cannot be greater than 10 and values of 'B' matrix cannot be greater than 20. 

In [6]:
#Ar no of Raw
#Ac no of columns 
Ar=int(input("Enter the no of raws in matrix : \n"))
Ac=int(input("Enter the no of Column's  in matrix : \n"))

#createing radom matrixes with conditions specified

A=np.random.randint(0,10,(Ar*Ac)).reshape(Ar,Ac)
A=np.matrix(A)
B=np.random.randint(0,20,(Ar*Ac)).reshape(Ar,Ac)
B=np.matrix(B)

#computing results
Sum=A+B
Diff=A-B

#printing the results
print("\nMatrix A:\n",A,"\n")
print("Matrix B:\n",B,"\n \nSum :\n",Sum,"\n\nDifference :\n",Diff)
type(A)

Enter the no of raws in matrix : 
3
Enter the no of Column's  in matrix : 
3

Matrix A:
 [[5 3 7]
 [4 0 7]
 [1 4 9]] 

Matrix B:
 [[16 10 16]
 [11 18 17]
 [10 18  8]] 
 
Sum :
 [[21 13 23]
 [15 18 24]
 [11 22 17]] 

Difference :
 [[-11  -7  -9]
 [ -7 -18 -10]
 [ -9 -14   1]]


numpy.matrix

## Question 6 :-
### Write a numpy program program to multiply two random matrices. The size of the matrices will a user input. All the matrix element should be a positive integer value. Suppose 'A' and 'B' are two matrix. All the value of 'A', 'B' matrices cannot be greater than 10.  

In [7]:
import numpy as np  #Numpy is imported as np

Ar,Ac,Br,Bc=map(int,input("Enter the no of Sizes of matrces (Seperated by a space)x : \n").split())

#Ar,Ac are the raw and column of matrix A simillarly Br and Bc are raw and column of matrix B 

A=np.random.randint(0,10,(Ar*Ac)).reshape(Ar,Ac) #Creating the matrix of given size with the random elements ie below 10
B=np.random.randint(0,10,(Br*Bc)).reshape(Br,Bc)  #Creating the matrix of given size with the random elements ie below 10

mulAb= np.matmul(A,B)            #matrix multiplication in numpy

print("\nMatrix : A \n",A,"\n\n","Matrix : B \n",B,"\nResult \n\n",mulAb) #printing the result in the prescrirbed format

Enter the no of Sizes of matrces (Seperated by a space)x : 
1 2 2 1

Matrix : A 
 [[3 7]] 

 Matrix : B 
 [[1]
 [5]] 
Result 

 [[38]]


# Question 7 :-
### Write a python program 4.py to take nXm matrix as a user input. 'n' and 'm' are command line argument which are separated by a space.
### Where n >= 3 and 0>=m<=7. If this condition is false, ask the user to enter the 'n' and 'm' again. Create a zero matrix with same dimension and convert all columns in the matrix into a fibonacci series.
### For ith column, the first element should be the sum of i+(i-1) value. Print this matrix on the terminal. ?

In [8]:
import numpy as np

def fibo(n): 
    a=0
    b=1
    fib=np.array([a,b])
    if(n<0): 
        print("Incorrect input") 
    elif (n==0): 
        return a 
    elif (n==1): 
        return b 
    else: 
        for i in range(2,n): 
            c=a+b
            #print(c)
            a=b 
            b=c 
            fib=np.append(fib,c)
        return fib 

while True:
    n,m=map(int,input("Enter the N and M of the NxM matrix : \n").split())
    if (not(n>=3 and (0<m<=7))):
        continue
    else:
        matA=np.zeros((n,m))
        
        for i in range(m):
            i+=1
            matA[0,i-1:i]=i+(i-1)
        for i in range(1,n):
            matA[i:,:]=fibo(m)
        print(matA)
        break

Enter the N and M of the NxM matrix : 
5 6
[[ 1.  3.  5.  7.  9. 11.]
 [ 0.  1.  1.  2.  3.  5.]
 [ 0.  1.  1.  2.  3.  5.]
 [ 0.  1.  1.  2.  3.  5.]
 [ 0.  1.  1.  2.  3.  5.]]
